kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "simple-pipeline"
spec:
  source:
    contextDir: simple-pipeline
    git:
      uri: "https://github.com/gmagnotta/ocp-tests"
      ref: "master"
    type: Git
  strategy:
    type: JenkinsPipeline 
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
